### PR TITLE
Update loopback-sdk-angular to latest v1.4.0

### PR DESCRIPTION
**Pull request by alexthewilde**

### CODE REVIEW

**Comment by zimlin** [comment]
I can merge this but we may want to update the tests as well.

At the moment, the generated file is tested against a known working version that has been generated ahead of time. Feel free to change this up if it's not the best approach.

**Comment by alexthewilde** [comment]
@zimlin what exactly needs to be changed to get this PR merged? thanks

**Comment by zimlin** [comment]
Update the tests

**Comment by alexthewilde** [comment]
Yeah I got that, but what exactly makes the tests fail?

**Comment by zimlin** [comment]
Oh.
Right now, it just checks against a per-generated file based off an empty app. The update probably generates a slightly different file.

Now that I'm thinking about it, I'm not entirely sure this is a great way to test it and if this even needs tests if loopback-sdk-angular is tested. I can probably just merge this in now.

**Comment by alexthewilde** [comment]
@zimlin that would be great if you merged this!

**Comment by alexthewilde** [comment]
@zimlin awesome. Are you also going to create a new npm release containing this change?

**Pull request merged**
